### ISSUE TITLE
Workflow failure test.yml

### ISSUE THREAD

**Issue by MikeMcC399** [bahmutov/cypress-gh-action-subfolders#46]
## Describe the bug

The workflow [.github/workflows/test.yml](https://github.com/bahmutov/cypress-gh-action-subfolders/blob/master/.github/workflows/test.yml) fails.

It logs the error:

"The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/"

See for instance run [2328352112](https://github.com/bahmutov/cypress-gh-action-subfolders/actions/runs/2328352112).

## Steps to reproduce the issue

Push to the repository to trigger the workflow.

## Expected behavior

The workflow should complete without errors.

## Suggested Fix

Update the reference in [.github/workflows/test.yml](https://github.com/bahmutov/cypress-gh-action-subfolders/blob/master/.github/workflows/test.yml) to

`uses: cypress-io/github-action@v5`

so that the current version (`v5`) of [github-action](https://github.com/cypress-io/github-action/) is used.

**Comment by MikeMcC399** [comment]
- PR #47 is submitted to resolve this issue

**Comment by bahmutov** [comment]
merged PR
